[project]
name = "scripts"
version = "0.0.1"
description = "Benchmark scripts for djangofmt against similar tools"
requires-python = ">=3.11"
authors = [
  { name = "Thibaut Decombe", email = "thibaut.d@gmail.com" },
]
dependencies = ["djade==1.7.0", "djhtml==3.0.10", "djlint==1.36.4"]
