# Simple workflow for deploying static content to GitHub Pages
# Based on astro github action deploy guide adding the wasm build parti
# See https://docs.astro.build/en/guides/deploy/github/
name: "[djangofmt] Publish Playground"

on:
  # Runs during release workflow
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run on PRs changing playground files (build only, no deploy)
  pull_request:
    paths:
      - "playground/**"

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions: { id-token: write, pages: write }

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    # Only use github-pages environment when not a PR
    environment: ${{ github.event_name != 'pull_request' && 'github-pages' || '' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Install Rust toolchain"
        run: rustup target add wasm32-unknown-unknown
      - uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa # v0.4.0
        with:
          version: v0.13.1
      - uses: jetli/wasm-bindgen-action@20b33e20595891ab1a0ed73145d8a21fc96e7c29 # v0.2.0
      - name: "Run wasm-pack build"
        run: wasm-pack build --target web crates/djangofmt_wasm --out-dir ../../playground/pkg
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
          package-manager-cache: false
      - name: Install dependencies
        run: npm ci
        working-directory: playground
      - name: Build
        run: npm run build
        working-directory: playground
      - name: Setup Pages
        if: github.event_name != 'pull_request'
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: "playground/dist"
      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
